/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activos.adminPresentation.agregar;

import activos.logic.Bien;
import activos.logic.SolicitudBien;
import java.awt.Graphics;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue R
 */
public class agregarView extends javax.swing.JFrame implements Observer {
    agregarModel model;
    agregarController controller;

    public agregarModel getModel() {
        return model;
    }

    public void setModel(agregarModel model) {
        this.model = model;
        this.model.addObserver(this);
    }

    public agregarController getController() {
        return controller;
    }

    public void setController(agregarController controller) {
        this.controller = controller;
    }
    
    /**
     * Creates new form agregarSolicitudView
     */
    public agregarView() {
        initComponents();
    }

      public void paint(Graphics g){
        super.paint(g);
        this.setTitle("Agregar Solicitud");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MarcaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ModeloTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PrecioUnitarioTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AgregarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescripcionTextField = new javax.swing.JTextPane();
        CantidadSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Descripcion :");

        jLabel2.setText("Marca :");

        jLabel3.setText("Modelo :");

        jLabel4.setText("Precio unitario :");

        PrecioUnitarioTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setText("Cantidad :");

        AgregarButton.setText("+");
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(DescripcionTextField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MarcaTextField)
                    .addComponent(ModeloTextField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecioUnitarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MarcaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ModeloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PrecioUnitarioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed

        Bien _bien = new Bien();
        List<Bien> lista = new ArrayList<>();
        SolicitudBien _solicitud = new SolicitudBien();
        double precio = 1.0;
        String marca = "", modelo = "", descripcion = "";
        int cantidad = 0;
        boolean res = true;
        do {
            try {
                _bien = new Bien();
                descripcion = this.DescripcionTextField.getText();
                if (descripcion.isEmpty()) {
                    throw new Exception("Campo de descripcion no puede estar vacio");
                }
                marca = this.MarcaTextField.getText();
                if (marca.isEmpty()) {
                    throw new Exception("Campo de marca no puede estar vacio");
                }
                modelo = this.ModeloTextField.getText();
                if (modelo.isEmpty()) {
                    throw new Exception("Campo de modelo no puede estar vacio");
                }
                String precioU = this.PrecioUnitarioTextField.getText();
                if (precioU.isEmpty()) {
                    throw new Exception("Campo de precio no puede estar vacio");
                }
                if (controller.esNumero(precioU)) {
                    precio = (double) Double.parseDouble(precioU);
                    cantidad = (Integer) this.CantidadSpinner.getValue();
                    if (cantidad == 0) {
                        throw new Exception("Cantidad no puede ser 0");
                    }
                } else {
                    throw new Exception("El precio ingresado contiene caracteres invalidos.");

                }

                for (int i = 0; i < cantidad; i++) {
                    _bien = new Bien(marca, modelo, descripcion, precio);
                    lista.add(_bien);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage());
                this.limpiar();

            }

            //Pregunta...

            int option = JOptionPane.showConfirmDialog(null, "Desea agregar mas bienes?", "Mensaje", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                res = true;
                limpiar();
            }
            if(option == JOptionPane.NO_OPTION){
                res = false;
            }

        } while (res);

        try {
            _solicitud = new SolicitudBien(new Date(), lista, 1);
            activos.data.SolicitudesDB.SolicitudAdd(_solicitud);

            for (int i = 0; i < cantidad; i++) {
                _bien = lista.get(i);
                activos.data.BienesDB.bienAdd(_bien);
            }

            JOptionPane.showMessageDialog(rootPane, "Solicitud ingresada correctamente");

            this.setVisible(false);

        } catch (SQLException ex) {
            Logger.getLogger(agregarView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(agregarView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AgregarButtonActionPerformed

    @Override
    public void update(Observable o, Object arg) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void limpiar(){
        this.CantidadSpinner.setValue(0);
        this.DescripcionTextField.setText("");
        this.MarcaTextField.setText("");
        this.ModeloTextField.setText("");
        this.PrecioUnitarioTextField.setText("");
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarButton;
    private javax.swing.JSpinner CantidadSpinner;
    private javax.swing.JTextPane DescripcionTextField;
    private javax.swing.JTextField MarcaTextField;
    private javax.swing.JTextField ModeloTextField;
    private javax.swing.JTextField PrecioUnitarioTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
