/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activos.jefePresentation.agregarR;

import activos.data.RelDatabase;
import activos.logic.Bien;
import activos.logic.Solicitud;
import activos.logic.Usuario;
import java.awt.Graphics;
import java.sql.SQLException;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrés
 */
public class AgregarRView extends javax.swing.JFrame implements Observer {
    /**
     * Creates new form AgregarRView
     */
    AgregarRModel model;
    AgregarRController controller;
    
    public AgregarRView() {
        initComponents();
    }
    public void paint(Graphics g){
        super.paint(g);
        this.setTitle("Registradores");
        try {
    muestraTabla();
    } catch (SQLException ex) {
        Logger.getLogger(AgregarRView.class.getName()).log(Level.SEVERE, null, ex);
    } catch (Exception ex) {
        Logger.getLogger(AgregarRView.class.getName()).log(Level.SEVERE, null, ex);
    }
        
       
    }

    
    
    private void muestraTabla() throws SQLException, Exception{
 
    List<Usuario> Usuarios = activos.data.UsuariosDB.getListaPorTipo(4);
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("Id");
    modelo.addColumn("Cedula del Funcionario");
    modelo.addColumn("Nombre de la dependencia");
    
    String[] datos = new String[3];
    for(Usuario usuario : Usuarios){
            
            datos[0] = "" + usuario.getId();
            datos[1]=""+ usuario.getFuncionario().getCedula();
            datos[2]= ""+ usuario.getDependencia().getNombre();
            modelo.addRow(datos);
        }
    
            this.jTable1.setModel(modelo);
            
            this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(100);
            this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(65);


    
    
}
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Asignar registrador seleccionado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Tabla de registradores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(255, 255, 255)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      model.getControladorPadre().getView().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    int rowIndex = 0; String id;
    try{
        rowIndex = this.jTable1.getSelectedRow();
        id = (String) this.jTable1.getValueAt(rowIndex, 0);
        }catch(Exception e){
        JOptionPane.showMessageDialog(rootPane, "No has seleccionado ninguna celda.");
        return;
    }
        
        List<Bien> bienes = null;
        try {
            bienes = activos.data.BienesDB.listaPorSolicitud(model.getSolicitud());
        } catch (Exception ex) {
            Logger.getLogger(AgregarRView.class.getName()).log(Level.SEVERE, null, ex);
        }
        for( Bien bien: bienes ){
                try {
                    activos.data.BienesDB.addRegistrador( bien.getCodigo(), activos.data.UsuariosDB.get(id));
                    activos.data.SolicitudesDB.setEstado(model.getSolicitud().getCodigoSolicitud(),4 );
                } catch (Exception ex) {
                    Logger.getLogger(AgregarRView.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
      JOptionPane.showMessageDialog(rootPane, "Registrador asignado correctamente");  
      model.getControladorPadre().getView().setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        this.repaint();
    }

    public AgregarRModel getModel() {
        return model;
    }

    public void setModel(AgregarRModel model) {
        this.model = model;
    }

    public AgregarRController getController() {
        return controller;
    }

    public void setController(AgregarRController controller) {
        this.controller = controller;
    }
    
}
