/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activos.registrador;

import activos.adminPresentation.AdminView;
import activos.data.RelDatabase;
import activos.logic.Solicitud;
import activos.registrador.verBienes.bienesController;
import activos.registrador.verBienes.bienesModel;
import activos.registrador.verBienes.bienesView;
import java.awt.Graphics;
import java.sql.SQLException;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josue R
 */
public class RegistradorView extends javax.swing.JFrame implements Observer {

    private RegistradorController controller;
    private RegistradorModel model;

    public RegistradorController getController() {
        return controller;
    }

    public void setController(RegistradorController controller) {
        this.controller = controller;
    }

    public RegistradorModel getModel() {
        return model;
    }

    public void setModel(RegistradorModel model) {
        this.model = model;
        model.addObserver(this);
    }
    
    
    public RegistradorView() {
        initComponents();
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        this.setTitle("Registrador");
        try {
            muestraTabla();
        } catch (Exception ex) {
        }
    }
    
    private void muestraTabla() throws SQLException, Exception{
     
        
       DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Fecha");
        modelo.addColumn("Precio Total");
        modelo.addColumn("Tipo");
        modelo.addColumn("Estado");
        
        String[] datos = new String[6];
        for(Solicitud solicitud : model.getSolicitudes()){
                
                datos[0] = "" + solicitud.getCodigoSolicitud();
                datos[1] = solicitud.getFecha().toString();
                datos[2] = "" + solicitud.getMontoTotal();
                int tipo =  solicitud.getTipo();
                switch(tipo){
                    case 1: datos[3] = "Compra"; break;
                    case 2: datos[3] = "Donacion"; break;
                    case 3: datos[3] = "Produccion"; break;
                    
                }
                int estado = solicitud.getEstado();
                switch(estado){
                    case 1: datos[4] = "Recibida"; break;
                    case 2: datos[4]= "Por verificar";break;
                    case 3: datos[4] = "Cancelada";break;
                    case 4: datos[4]= "Procesada";break;
                    case 5: datos[4] = "Espera de rotulacion";break;
                }
                modelo.addRow(datos);
            }
        
                this.jTable1.setModel(modelo);
                
                this.jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
                this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
                this.jTable1.getColumnModel().getColumn(2).setPreferredWidth(15);
                this.jTable1.getColumnModel().getColumn(3).setPreferredWidth(15);
                this.jTable1.getColumnModel().getColumn(4).setPreferredWidth(20);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Solicitudes pendientes para su registro :");

        jButton1.setText("Seleccionar Solicitud");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int rowIndex = 0;int codigo = 0;
        try{
         rowIndex = this.jTable1.getSelectedRow();
         codigo = Integer.parseInt((String) this.jTable1.getValueAt(rowIndex, 0));
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "No has seleccionado ninguna celda.");
            return;
        }
        try {
            model.initTrioVerBienes(codigo);
            model.getModel_bienes().setControladorPadre(controller);
            model.getView_bienes().setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            Logger.getLogger(AdminView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    @Override
    public void update(Observable o, Object arg) {
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
